#Example Service
#Rename to config.services.yaml and add your services
services:
    - name: spyName
      host: spyHost.live.com
      user: spyUser
      port: 22
      krb5_conf_path: /etc/kerb5.conf
      files:
          - alias: spy-1
            path: /var/log/spyPath.log
          - alias: spy-2
            path: /var/log/spyPath.log
